create table tb_aluno (id int8 generated by default as identity, class_mate varchar(255), name varchar(255), primary key (id));
create table tb_aluno (id int8 generated by default as identity, class_mate varchar(255), name varchar(255), primary key (id));
create table tb_aluno (id int8 generated by default as identity, class_mate varchar(255), name varchar(255), primary key (id));
create table tb_aluno (id int8 generated by default as identity, class_mate varchar(255), name varchar(255), primary key (id));
create table tb_aluno (id int8 generated by default as identity, class_mate varchar(255), name varchar(255), primary key (id));
create table tb_aluno (id int8 generated by default as identity, class_mate varchar(255), name varchar(255), primary key (id));
